# Generated by Django 4.0.6 on 2022-08-26 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSMS', '0002_remove_approvals_item_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name=str)),
                ('product_id', models.CharField(max_length=20, verbose_name=str)),
                ('product_quantity', models.IntegerField(default=0)),
                ('brand', models.CharField(max_length=50, verbose_name=str)),
            ],
        ),
    ]
