# Generated by Django 4.0.6 on 2022-08-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSMS', '0004_product_rename_approvals_approval_delete_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Engines', 'Engines'), ('IT Equipment', 'IT Equipment'), ('Phone', 'Phone')], max_length=50, null=True),
        ),
    ]
