# Generated by Django 4.0.6 on 2022-08-31 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSMS', '0005_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
