# Generated by Django 4.0.6 on 2022-09-02 02:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSMS', '0006_alter_product_brand_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateField(default=datetime.date(2022, 9, 2), verbose_name='Date'),
            preserve_default=False,
        ),
    ]
