# Generated by Django 4.0.6 on 2022-09-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSMS', '0008_remove_product_date_alter_product_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_quantity',
            field=models.IntegerField(null=True),
        ),
    ]
