# Generated by Django 4.0.6 on 2022-09-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSMS', '0009_alter_product_product_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approvals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('product_quantity', models.IntegerField(default=1)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('product_quantity', models.IntegerField(default=1)),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Approval',
        ),
    ]
