# Generated by Django 4.0.6 on 2022-09-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSMS', '0010_approvals_orders_delete_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvals',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
        migrations.AddField(
            model_name='orders',
            name='ordered',
            field=models.BooleanField(default=False, verbose_name='Ordered'),
        ),
    ]
