# Generated by Django 4.0.6 on 2022-09-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSMS', '0012_rename_brand_orders_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
