# Generated by Django 4.0.6 on 2022-09-08 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSMS', '0013_orders_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
